Revert "power: qpnp-smb2: Implement battery charging_enabled node"
ASUS driver already had this. Remove it!

errors:
../drivers/power/supply/qcom/qpnp-smb2.c: In function 'smb2_batt_get_prop':
../drivers/power/supply/qcom/qpnp-smb2.c:1007:9: error: duplicate case value
 1007 |         case POWER_SUPPLY_PROP_CHARGING_ENABLED:
      |         ^~~~
../drivers/power/supply/qcom/qpnp-smb2.c:1000:9: note: previously used here
 1000 |         case POWER_SUPPLY_PROP_CHARGING_ENABLED:
      |         ^~~~
../drivers/power/supply/qcom/qpnp-smb2.c: In function 'smb2_batt_set_prop':
../drivers/power/supply/qcom/qpnp-smb2.c:1133:9: error: duplicate case value
 1133 |         case POWER_SUPPLY_PROP_CHARGING_ENABLED:
      |         ^~~~
../drivers/power/supply/qcom/qpnp-smb2.c:1126:9: note: previously used here
 1126 |         case POWER_SUPPLY_PROP_CHARGING_ENABLED:
      |         ^~~~

This reverts commit 094b738f46c80c56d03d923c3e780e071abe34b0.

Signed-off-by: wimbiyoashizkia <wimbiyoashizkia@yahoo.com>